# Can be used in the test data like ${MyObject()} or ${MyObject(1)}

#交款申请
新建交款申请="//button[@id='btnAdd']"
管理区下拉框="//select[@id='RegionId']"
下拉框选择管理区="//select[@id='RegionId']//option[2]"
交款数据存在断言="//div[@id='gridProject']//table[@class='k-selectable']/tbody/tr[1]/td[1]"
明细数据存在断言="//div[@id='gridDetail']//tbody/tr[1]/td[1]"
项目数据存在断言="//div[@id='gridItemTypeDetail']//tr[1]/td[1]"
导出excel="//button[@id='btnExportProject']"
导出明细excel="//button[@id='btnExportDetail']"
导出项目excel="//button[@id='btnExportItemTypeDetail']"
收款明细="//ul[@class='nav nav-tabs']/li[2]/a"
项目明细="//ul[@class='nav nav-tabs']/li[3]/a"
交款备注="//textarea[@id='Remark']"
保存交款="//button[@id='btnSave']"
交款成功断言="//div[text()='提交轧账成功！']"
确定交款成功="//div[@class='modal-dialog']//button[@class='btn btn-primary']"
搜索交款申请="//button[@id='btnFilter']"
选择交款申请="//div[@id='gridAccountStatement']//td[text()='未审核']/../td[1]//input"
交款申请编辑="//button[@id='btnEdit']"
更新成功断言="//div[text()='更新轧账成功！']"
交款申请查看明细="//button[@id='btnDetail']"
查看明细返回="//a[@class='btn btn-default']"
审核交款申请="//button[@id='btnConfirm']"
审核成功断言="//div[text()='审核成功！']"
审核成功确定="//div[@class='modal-dialog']//button[@class='btn btn-primary']"
撤销交款审核="//button[@id='btnUndoAudit']"
选择已审核交款="//div[@id='gridAccountStatement']//td[text()='已审核']/../td[1]//input"
撤销审核成功断言="//div[text()='撤销审核成功！']"
撤销审核确定="//div[@class='modal-dialog']//button[@class='btn btn-primary']"
撤销扎帐="//button[@id='btnCancel']"
撤销成功断言="//div[text()='1条记录撤销成功！']"
撤销扎帐确定="//div[@class='modal-dialog']//button[@class='btn btn-primary']"
