#催费通知单
管理区下拉="//select[@id='RegionId']"
下拉选择管理区="//select[@id='RegionId']/option[@value='3']"#未引用
客户名称输入框="//input[@id='CustomerName']"
房间名称输入框="//input[@id='HouseNumber']"
收费日期输入框="//input[@id='ChargeDate']"
确认日期="//button[@class='applyBtn btn btn-small btn-sm btn-success']"
选择秒左="//div[@class='calendar left']//select[@class='minuteselect']"
选择00秒左="//div[@class='calendar left']//select[@class='minuteselect']/OPTION[@selected]/preceding-sibling::option[1]"
选择秒右="//div[@class='calendar right']//select[@class='minuteselect']"
选择60秒右="//div[@class='calendar right']//select[@class='minuteselect']/OPTION[@selected]/following-sibling::option[1]"
搜索按钮="//button[@id='btnFilterDetail']"
导出excel="//button[@id='btnExport']"
展开明细="//div[@id='PaymentHistory']//tr[1]/td[1]/a"
查看票据="//div[@id='PaymentHistory']//li[2]/span[@class='k-link']"
更改票号="//div[@id='PaymentHistoryTicketDetails']//tbody//a[5]"
更改票号输入框="//input[@id='newTicketNumber']"
确认修改="//form[@id='changeTicketNumberForm']//button[@class='btn btn-primary update']"
再次确认修改="//div[@class='modal-dialog']//button[@class='btn btn-primary']"
修改成功断言="//div[text()='修改成功!']"
修改成功确认="//div[@class='modal-dialog']//button[@class='btn btn-primary']"
补打按钮="//div[@id='PaymentHistoryTicketDetails']//tbody//a[4]"
作废并重打按钮="//div[@id='PaymentHistoryTicketDetails']//tbody//a[3]"
确认单不打印="//button[@id='btnPaymentConfirm']"
确定并开始打印="//button[@id='btnPaymentConfirmAndPrint']"
撤销收费="//a[@class='undoCharge']"
撤销回收票据="//button[@id='bntCallbackTicketConfirm']"
回收票据失败断言="//strong[@id='errorMessage']"
撤销不回收票据="//button[@id='bntNotCallbackTicketConfirm']"
撤销收费成功="//div[text()='收费撤销成功！']"
撤销成功确定="//div[@class='modal-dialog']//button[@class='btn btn-primary']"
已撤销的再撤销断言="//div[text()='该收费记录已经撤销,不能反复撤销！']"
撤销成功数据断言="//td[text()='已撤销']"
按房间车位收费历史="//li[2]/a[@class='ajaxify']"
数据存在判断="//div[@id='PaymentHistory']//tr[@class='k-master-row']/td[4]"
票据数据存在断言="//table/tbody/tr[@class='k-master-row'][1]/td[6]"
按票据搜索收费历史="//li[3]/a[@class='ajaxify']"
票据号输入框="//input[@id='TicketNumber']"
退款撤销断言="//strong[text()='已经退款不能撤销！']"
