#票据管理
##票据本管理
新建票据管理="//button[@class='ant-btn ant-btn-primary'][1]"
票据名称输入框="//input[@id='name']"
票据管理区下拉="//div[@id='regionId']//div[@class='ant-select-selection__placeholder']"
选择票据管理区="//ul[@class='ant-select-dropdown-menu  ant-select-dropdown-menu-root ant-select-dropdown-menu-vertical']/li[1]"
保存票据="//button[@class='ant-btn ant-btn-primary']"
高级搜索="//a[@class='seniorSearchBtn']"
票据名称="//input[@id='name']"
确认搜索按钮="//form[@class='ant-form ant-form-horizontal']//button[@class='ant-btn ant-btn-primary']"
勾选可见="//tbody/tr[1]/td[1]"
勾选票据="//tbody/tr[1]/td[1]//input"
编辑票据="//button[@class='ant-btn ant-btn-primary'][2]"
标记为已用完="//button[@class='ant-btn ant-btn-primary'][3]"
查看使用明细="//button[@class='ant-btn ant-btn-primary'][4]"
删除票据="//button[@class='ant-btn ant-btn-primary'][5]"
确认删除="//button[@class='ant-btn ant-btn-primary ant-btn-sm']"
成功断言="//div[@class='ant-message-custom-content ant-message-success']/span"
删除成功="//span[text()='1条记录删除成功！']"

##损毁票据登记
新增损毁票据按钮="//button[@class='ant-btn ant-btn-primary']"
请选择票据本下拉="//div[@class='ant-select-selection__rendered']/div[@class='ant-select-selection__placeholder']"
下拉选择票据本="//div[3]//ul[@role='listbox']//li[1]"
损毁票据名称="//input[@id='ticketId']"
损毁票据号="//textarea[@id='invalidNumber']"
保存损毁票据号="//div[@class='ant-modal whiteSpaceNormalTable']//button[@class='ant-btn ant-btn-primary']"
勾选票据="//tbody/tr[1]/td[1]//input"
删除损毁票据按钮="//div[@class='ant-col ant-col-16']/button[@class='ant-btn ant-btn-primary'][2]"
