#经营性收费
##收费
客户搜索栏="//span[@id='select2-CustomerId-container']/span"
客户搜索栏输入框="//span[@class='select2-dropdown select2-dropdown--below']//input"
下拉选择客户="//ul[@id='select2-CustomerId-results']/li[1]/div"
添加临时费用="//button[@id='btnAddCost']"
标准搜索栏="//span[@id='select2-TemporaryCostChargeItem-container']"
标准搜索栏输入框="//span[@class='select2-dropdown select2-dropdown--below']//input[@class='select2-search__field']"
下拉选择收费标准="//ul[@id='select2-TemporaryCostChargeItem-results']/li[1]"
选择开始时间按钮="//form[@id='temporaryCostForm']//div[@class='form-group'][4]//button"
选择开始时间="//div[@class='datetimepicker datetimepicker-dropdown-top-left dropdown-menu'][1]//tbody/tr[4]/td[@class='day'][2]"
选择结束时间按钮="//form[@id='temporaryCostForm']//div[@class='form-group'][5]//button"
选择结束时间="//div[@class='datetimepicker datetimepicker-dropdown-top-left dropdown-menu'][2]//tbody/tr[4]/td[@class='day'][2]"
经营性金额输入框="//input[@id='Amount']"
确认添加="//div[@id='temporaryCostWindow']//button[@class='btn btn-primary btnOkWindow']"
添加成功断言="//div[text()='添临时性收费成功！']"
确认添加成功="//div[@class='modal-dialog']//button[@class='btn btn-primary']"
选择付款方式="//span[@id='select2-PaidMethodId-container']"
付款方式现金="//ul[@id='select2-PaidMethodId-results']/li[1]"
确认收款="//button[@id='btnPaymentPreview']"
确认但不打印="//button[@id='btnPaymentConfirm']"
收费成功断言="//div[text()='收费成功！']"
确认收费成功="//div[@class='modal-dialog']//button[@class='btn btn-primary']"
##添加客户
添加客户按钮="//button[@id='btnAddCustomer']"
管理区下拉框="//select[@id='CustomerRegionId']"
下拉框选择管理区="//select[@id='CustomerRegionId']//option[2]"
客户类型下拉框="//span[@id='select2-CustomerTypeId-container']"
下拉选择客户类型="//ul[@id='select2-CustomerTypeId-results']/li[1]"
客户名称输入框="//div[@class='col-md-6'][1]//input[@id='CustomerName']"
确认添加客户="//button[@id='btnConfirmAddCustomer']"
创建客户成功断言="//div[text()='创建客户成功']"
确认客户创建成功="//div[@class='modal-dialog']//button[@class='btn btn-primary']"


