#预缴费
预缴按钮="//button[@id='btnAdd']"
搜索栏="//span[@id='select2-CustomerId-container']/span[@class='select2-selection__placeholder']"
搜索栏输入框="//span[@class='select2-dropdown select2-dropdown--below']//input"
下拉选择客户="//ul[@id='select2-CustomerId-results']/li[1]"
预缴_房间下拉框="//input[@id='HouseId']/.."#选择房间数据#//ul/li[text()='${YCKCode}']
预存款输入框="//input[@id='Balance']"
选择预存款账户="//span[@id='select2-ChargeItemTypeId-container']"
选择通用账户="//ul[@id='select2-ChargeItemTypeId-results']/li[1]"
选择付款方式="//span[@id='select2-PaidMethodId-container']"
付款方式现金="//ul[@id='select2-PaidMethodId-results']/li[1]"
确认收款="//button[@id='btnPaymentPreview']"
确认但不打印="//button[@id='btnPaymentConfirm']"
充值成功断言="//div[text()='预存款充值成功！']"
确定充值成功="//div[@class='bootbox modal bootbox-alert in']//button[@class='btn btn-primary']"
##冲抵欠费
预存款账户搜索="//input[@id='searchTerm']"
选择账户账单="//tbody/tr[1]/td[1]/div/span"
确认搜索="//button[@id='btnFilter']"
选择账户="//tbody/tr[1]/td[3]"
冲抵欠费按钮="//button[@id='btnPayBill']"
确认冲抵收费="//button[@id='btnAdvancePayConfirm']"
收费成功断言="//div[text()='收费成功！']"
查看收支明细="//button[@id='btnDetail']"
选择支出="//div[@id='gridDetail']//td[text()='支出']"
查看支出明细="//button[@id='btnDetail']"
关闭支出明细="//div[@id='ViewBillDetailWindow']//button[@class='btn btn-default']"
欠费冲抵返回="//div[@class='page-content-body']//a[@class='btn btn-primary']"
查看核销明细="//button[@id='btnViewBillDetail']"
出现核销账单="//div[@id='gridViewBillDetail']//tbody/tr[1]/td[1]"
勾选核销账单="//div[@id='gridViewBillDetail']//div[@class='k-link']//input"
批量打印票据="//button[@id='btnBatchPrint']"
确定并开始打印="//button[@id='btnPaymentConfirmAndPrint']"
预存款退款="//button[@id='refund']"
退款金额输入框="//input[@id='Amount']"
退款原因="//textarea[@id='Reason']"
退款保存="//button[@id='btnSave']"
退款成功断言="//div[text()='退款成功！！']"
确定退款="//div[@class='bootbox modal bootbox-alert in']//button[@class='btn btn-primary']"

