# Can be used in the test data like ${MyObject()} or ${MyObject(1)}
class MyObject:
    def __init__(self, index=''):
        self.index = index
    def __str__(self):
        return '<MyObject%s>' % self.index
    


账号输入框="//input[@type='text']"
密码输入框="//input[@type='password']"
##########收支科目##########
收支科目新建按钮="//button/span[text()='新 建']/.."
新建收支科目名称="//input[@id='name']"
新建收支科目类型下拉="//form//div[@class='ant-select ant-select-enabled']"
选择科目类型收入="//ul/li[text()='收入']"
选择科目类型支出="//ul/li[text()='支出']"
新建收支科目备注="//input[@id='remark']"
新建收支科目确定="//div[@class='ant-modal-footer']//button[2]"
收支科目简单搜索输入框="//input[@class='ant-input ant-input-lg']"
收支科目简单搜索按钮="//span[@class='ant-input-suffix']"
收支科目编辑按钮="//tbody/tr[1]/td[6]//span/span/a"
收支科目删除按钮="//tbody/tr[1]/td[6]/span/a"
选择一条收支科目数据="//tbody/tr[1]/td[1]//input"
收支科目批量删除按钮="//button[@class='ant-btn']"
收支科目删除确认按钮="//button[@class='ant-btn ant-btn-primary ant-btn-sm']"
收支科目高级搜索展开="//a[@class='seniorSearchBtn']"
科目名称输入框="//input[@id='name']"
科目类型下拉框="//div[@id='type']"
科目类型下拉框选择收入="//div[@id='type']/following-sibling::div[1]//ul/li[1]"
科目备注输入框="//input[@id='remark']"    #科目创建时间选择框="//span[@id='createdDate']"
收支科目高级搜索按钮="//div/button[@class='ant-btn ant-btn-primary']"
##########收入登记##########
收入登记新建按钮="//button/span[text()='新 建']/.."
新建收入登记管理区下拉框="//div[@id='regionId']"
新建收入登记选择管理区="//ul[@role='listbox']/li[1]"
新建收入登记科目名称下拉框="//div[@id='accountId']"
新建收入登记选择科目名称="//div[@style='position: absolute; top: 0px; left: 0px; width: 100%;'][2]//ul[@role='listbox']/li[1]"
新建收入登记金额="//input[@id='amount']"
新建收入登记发生日期选择框="//span[@id='accountingDate']"
新建收入登记发生日期选择今天="//span[@class='ant-calendar-footer-btn']"
新建收入登记备注="//input[@id='remark']"
新建收入登记确定="//div[@class='ant-modal-footer']//button[2]"
收入登记简单搜索输入框="//input[@class='ant-input ant-input-lg']"
收入登记简单搜索按钮="//span[@class='ant-input-suffix']"
收入登记编辑按钮="//tbody/tr[1]/td[9]//span/span/a"
收入登记删除按钮="//tbody/tr[1]/td[9]/span/a"
选择一条收入登记数据="//tbody/tr[1]/td[1]//input"
收入登记批量删除按钮="//button[@class='ant-btn']"
收入登记删除确认按钮="//button[@class='ant-btn ant-btn-primary ant-btn-sm']"
收入登记高级搜索展开="//a[@class='seniorSearchBtn']"
收入登记搜索管理区下拉框="//div[@id='regionId']"
收入登记搜索选择管理区="//div[@id='regionId']/following-sibling::div//ul[@role='listbox']/li[1]"
收入科目名称下拉框="//div[@id='accountId']"
选择收入科目名称="//div[@id='accountId']/following-sibling::div//ul[@role='listbox']/li[1]"
收入科目备注输入框="//input[@id='remark']"
收入登记高级搜索按钮="//div/button[@class='ant-btn ant-btn-primary']"
##########支出登记##########
支出登记新建按钮="//button/span[text()='新 建']/.."
新建支出登记管理区下拉框="//div[@id='regionId']"
新建支出登记选择管理区="//ul[@role='listbox']/li[1]"
新建支出登记科目名称下拉框="//div[@id='accountId']"
新建支出登记选择科目名称="//div[@style='position: absolute; top: 0px; left: 0px; width: 100%;'][2]//ul[@role='listbox']/li[1]"
新建支出登记金额="//input[@id='amount']"
新建支出登记发生日期选择框="//span[@id='accountingDate']"
新建支出登记发生日期选择今天="//span[@class='ant-calendar-footer-btn']"
新建支出登记备注="//input[@id='remark']"
新建支出登记确定="//div[@class='ant-modal-footer']//button[2]"
支出登记简单搜索输入框="//input[@class='ant-input ant-input-lg']"
支出登记简单搜索按钮="//span[@class='ant-input-suffix']"
支出登记编辑按钮="//tbody/tr[1]/td[9]//span/span/a"
支出登记删除按钮="//tbody/tr[1]/td[9]/span/a"
选择一条支出登记数据="//tbody/tr[1]/td[1]//input"
支出登记批量删除按钮="//button[@class='ant-btn']"
支出登记删除确认按钮="//button[@class='ant-btn ant-btn-primary ant-btn-sm']"
支出登记高级搜索展开="//a[@class='seniorSearchBtn']"
支出登记搜索管理区下拉框="//div[@id='regionId']"
支出登记搜索选择管理区="//div[@id='regionId']/following-sibling::div//ul[@role='listbox']/li[1]"
支出科目名称下拉框="//div[@id='accountId']"
选择支出科目名称="//div[@id='accountId']/following-sibling::div//ul[@role='listbox']/li[1]"
支出科目备注输入框="//input[@id='remark']"
科目类型下拉框选择支出="//div[@id='type']/following-sibling::div[1]//ul/li[1]"
支出登记高级搜索按钮="//div/button[@class='ant-btn ant-btn-primary']"
##########收支综合统计##########
收支综合统计管理区下拉框="//div[@id='regionId']"
收支综合统计选择管理区="//div[@id='regionId']/following-sibling::div//ul[@role='listbox']/li[1]"
收支综合统计发生时间选择框="//span[@id='accountingDate']"
收支综合统计发生日期选择今天="//span[text()='今天']"
收支综合统计搜索按钮="//div/button[@class='ant-btn ant-btn-primary']"
