# Can be used in the test data like ${MyObject()} or ${MyObject(1)}
class MyObject:
    def __init__(self, index=''):
        self.index = index

    def __str__(self):
        return '<MyObject%s>' % self.index

账号输入框="//input[@type='text']"
密码输入框="//input[@type='password']"
##########应收月度统计##########
应收月度统计_资源树搜索框="//input[@id='txtSerachTerm']"
应收月度统计_选择年份下拉框="//select[@id='year']"
应收月度统计_选择年份="//select[@id='year']/option[1]"
应收月度统计_选择月份="//div[@id='monthSelector']//label[1]"#input[1-12]分别对应1-12月
应收月度统计_搜索按钮="//button[@id='btnSearch']"
应收月度统计_一条数据的资源代码="//div[@id='gridReceivableMonthDetail']//tbody/tr[1]/td[1]/a"
应收月度统计_资源详情页面="//h2"
应收月度统计_一条数据的客户="//div[@id='gridReceivableMonthDetail']//tbody/tr[1]/td[3]/a"
应收月度统计_客户详情页面客户名称="//div[@class='ant-card-body']/div[1]/div[1]/span[2]"
应收月度统计_指定收费项目="//input[@class='select2-search__field']"
应收月度统计_选择一个收费项目="//ul[@id='select2-ChargeItemTypeIds-results']/li[1]"
应收月度统计_汇总到楼宇勾选框="//input[@id='BuildingName']"
应收月度统计_所有管理区展开="//tbody/tr/td[1]/span[@class='k-icon k-i-arrow-e']"
应收月度统计_所有楼宇展开="//tbody/tr[1]/td[3]/span[1]"
应收月度统计_汇总到收费项目勾选框="//input[@id='ChargeItemTypeName']"
应收月度统计_所有应收展开="//tbody/tr[1]/th[1]/span[1]"
应收月度统计_期初欠费所有项目展开="//div[@id='pivotgridReceivableMonth']//tbody/tr[3]/th[1]/span[1]"
应收月度统计_本期应收所有项目展开="//div[@id='pivotgridReceivableMonth']//tbody/tr[3]/th[2]/span[1]"
应收月度统计_导出Excel按钮="//button[@id='btnExport']"
##########欠费月度统计##########
欠费月度统计_资源树搜索框="//input[@id='txtSerachTerm']"
欠费月度统计_指定收费项目="//input[@class='select2-search__field']"
欠费月度统计_费用应收日期开始="//input[@id='ShouldChargeStartDate']"
欠费月度统计_费用应收日期结束="//input[@id='ShouldChargeEndDate']"
欠费月度统计_选择一个收费项目="//ul[@id='select2-ChargeItemTypeIds-results']/li[1]"
欠费月度统计_搜索按钮="//button[@id='btnSearch']"
欠费月度统计_汇总导出按钮="//button[@id='btnExport']"
欠费月度统计_汇总Tab="//ul[@id='tabHeader']/li[1]"
欠费月度统计_汇总到楼宇勾选框="//input[@id='BuildingName']"
欠费月度统计_所有管理区展开="//tbody/tr/td[1]/span[@class='k-icon k-i-arrow-e']"
欠费月度统计_所有楼宇展开="//tbody/tr[1]/td[3]/span[1]"
欠费月度统计_所有欠费金额="//tbody/tr[1]/td[1]/a"
欠费月度统计_汇总到收费项目勾选框="//input[@id='ChargeItemTypeName']"
欠费月度统计_所有项目展示="//tbody/tr[1]/th[1]/span[@class='k-icon k-i-arrow-e']"
欠费月度统计_客户资源汇总Tab="//ul[@id='tabHeader']/li[2]"
欠费月度统计_客户资源汇总导出按钮="//button[@id='btnExportCustomerSheetSummary']"
欠费月度统计_客户资源汇总查看房间信息="//tbody/tr[1]/td[2]/a"
欠费月度统计_资源详情页面="//h2"
欠费月度统计_客户资源汇总查看客户信息="//tbody/tr[1]/td[5]/a"
欠费月度统计_客户详情页面客户名称="//div[@class='ant-drawer-body']/div[1]/div[1]/div[1]//div[@class='ant-card-body']/div[1]/div[1]/span[2]"
欠费月度统计_客户资源明细Tab="//ul[@id='tabHeader']/li[3]"
欠费月度统计_导出欠费明细按钮="//button[@id='btnExportCustomerSummary']"
欠费月度统计_导出欠费汇总按钮="//button[@id='btnExportCustomerSummaryWithoutDetails']"
欠费月度统计_客户资源明细查看房间信息="//tbody/tr[1]/td[4]/a"
欠费月度统计_客户资源明细查看客户信息="//tbody/tr[1]/td[7]/a"
欠费月度统计_清单明细Tab="//ul[@id='tabHeader']/li[4]"
欠费月度统计_清单明细导出按钮="//button[@id='btnExportDetail']"
欠费月度统计_清单明细查看房间信息="//tbody/tr[1]/td[2]/a"
欠费月度统计_清单明细查看客户信息="//tbody/tr[1]/td[6]/a"
##########已收费用月统计##########
已收费用月统计_资源树搜索框="//input[@id='txtSerachTerm']"
已收费用月统计_选择年份下拉框="//select[@id='year']"
已收费用月统计_选择年份="//select[@id='year']/option[1]"
已收费用月统计_选择月份="//div[@id='monthSelector']//label[1]"#label[1-12]分别对应1-12月
已收费用月统计_指定收费项目="//input[@class='select2-search__field']"
已收费用月统计_选择一个收费项目="//ul[@id='select2-ChargeItemTypeIds-results']/li[1]"
已收费用月统计_搜索按钮="//button[@id='btnSearch']"
已收费用月统计_收费汇总导出按钮="//button[@id='btnExportSummary']"
已收费用月统计_票据汇总Tab="//ul[@id='tabHeader']/li[2]"
已收费用月统计_票据汇总导出按钮="//button[@id='btnExportTicket']"
已收费用月统计_收费明细Tab="//ul[@id='tabHeader']/li[3]"
已收费用月统计_收费明细导出按钮="//button[@id='btnExportDetail']"
已收费用月统计_收费明细查看房间信息="//tbody/tr[1]/td[1]/a"
已收费用月统计_房间详情页面验证="//h2"
已收费用月统计_收费明细查看客户信息="//tbody/tr[1]/td[3]/a"
已收费用月统计_客户详情页面验证="//div[@class='ant-drawer-body']/div[1]/div[1]/div[1]//div[@class='ant-card-body']/div[1]/div[1]/span[2]"
##########收入月度分摊##########
收入月度分摊_资源树搜索框="//input[@id='txtSerachTerm']"
收入月度分摊_选择年份下拉框="//select[@id='year']"
收入月度分摊_选择年份="//select[@id='year']/option[1]"
收入月度分摊_选择月份="//div[@id='monthSelector']//label[1]"#label[1-12]分别对应1-12月
收入月度分摊_指定收费项目="//input[@class='select2-search__field']"
收入月度分摊_选择一个收费项目="//ul[@id='select2-ChargeItemTypeIds-results']/li[1]"
收入月度分摊_搜索按钮="//button[@id='btnSearch']"
收入月度分摊_导出汇总按钮="//button[@id='btnExport']"
收入月度分摊_导出明细按钮="//button[@id='btnDetailExport']"
收入月度分摊_点击本期收往期非金额="//tbody/tr[1]/td[3]/a[1]"
收入月度分摊_查看资源代码详情="//*[@id='gridChargeMonthDetail']/div[2]/table/tbody/tr[1]/td[1]/a"
收入月度分摊_查看客户详情="//*[@id='gridChargeMonthDetail']/div[2]/table/tbody/tr[1]/td[3]/a"
收入月度分摊_资源详情页面="//h2"
收入月度分摊_客户详情页面客户名称="//div[@class='ant-drawer-body']/div[1]/div[1]/div[1]//div[@class='ant-card-body']/div[1]/div[1]/span[2]"
'''
新增报表通用
'''
#通用按钮
搜索按钮="//span[text()='搜 索']/.."
查询按钮="//span[text()='查 询']/.."
重置按钮="//span[text()='重 置']/.."
导出按钮="//span[text()='导出EXCEL']/.."
#通用管理区定位
管理区下拉="//span[text()='请选择管理区']/.."
div管理区下拉="//div[text()='请选择管理区']/.."
勾选第一个管理区="//li[@class='ant-select-tree-treenode-switcher-close'][1]//span[@class='ant-select-tree-checkbox-inner']"
点击第一个管理区="//ul[@role='listbox']/li[1]"
#通用搜索条件定位
收费项目下拉="//div[text()='请选择收费项目']"
选择对应的收费项目="//li[text()='租金']"
应收月份日期拉下="//span[@id='month']"
选择开始日期="//input[@placeholder='开始月份']/../../..//tr[1]/td[1]"
选择结束日期="//input[@placeholder='开始月份']/../../..//tr[5]/td[1]"
年份选择下拉="//span[@id='targetYear']"
选择当前年="//td[@class='ant-calendar-year-panel-cell ant-calendar-year-panel-selected-cell']/a"
#通用高级搜索条件定位
高级搜索展开="//a[@class='seniorSearchBtn']"
显示收费标准="//span[text()='显示收费标准']/..//span/input"
展示收费标准="//span[text()='展示收费标准']/..//span/input"
按收费标准汇总="//span[text()='按收费标准汇总']/..//span/input"
按月汇总="//span[text()='按月汇总']/..//span/input"
不为零的合计列数据="//td[text()='合计']/../td[*!=0][1]//a"
收费标准断言="//span[text()='收费标准']"
应收月份断言="//span[text()='应收月份']"
##########月度收费统计##########
月份下拉="//span[@id='month']/div/input[@class='ant-calendar-picker-input ant-input']"
数据断言="//td[text()='租金']"
span数据断言="//span[text()='租金']"
断言打开明细="//span[@class='title___RImDz']"
##########按月环比收费##########
按月环比明细数据入口="//span[text()='实际应收']/../../../../../..//tr[1]//td[*!=0][1]/a"
按月环比明细断言="//span[@class='title___RImDz']"
##########年度历史收费###########
##########本年收费率欠费率##########
截止日期="//span[@id='filterChargeDateEnd']"
本年收欠率截止日期="//input[@placeholder='请选择截止日期']/../../..//tr[1]/td[1]"
本年收欠率截报表选择收费项目="//tr[1]//td//a[1]"
本年收费欠费率明细数据断言="//span[text()='收欠费明细']"
本年收费欠费率明细搜索="//input[@placeholder='楼宇/车库/资源代码/房间状态/费用承担人']/../span"
##########收费目标完成率###########
截止日期当前日期="//td[@class='ant-calendar-cell ant-calendar-today ant-calendar-selected-date ant-calendar-selected-day']/div[@class='ant-calendar-date']"
##########欠费原因统计##########
欠费原因截止日期="//span[@id='paidDate']"
欠费原因截止日期选择="//a[text()='今天']"
欠费原因应收日期="//span[@id='date']"
欠费原因选择应收开始日期="//input[@placeholder='开始日期']/../../..//tr[1]/td[1]"
欠费原因选择应收结束日期="//input[@placeholder='开始日期']/../../..//tr[5]/td[1]"
欠费原因明细断言="//span[@class='title___RImDz']"
###########年度收费目标管理##########
新建按钮="//span[text()='新 建']/.."
编辑按钮="//tr[1]//a[text()='编辑']"
删除按钮="//tr[1]//a[text()='删除']"
新建页面选择年份="//input[@placeholder='请输入收本年目标金额']/../../../../../../../../..//span[@id='targetYear']"
新建页面管理区下拉="//input[@placeholder='请输入收本年目标金额']/../../../../../../../../..//div[text()='请选择管理区']"
新建页面收费项目下拉="//input[@placeholder='请输入收本年目标金额']/../../../../../../../../..//div[text()='请选择收费项目']"
收本年目标金额="//input[@placeholder='请输入收本年目标金额']"
收历欠目标金额="//input[@placeholder='请输入收历欠目标金额']"
保存按钮="//span[text()='保 存']/.."
二次确定="//div[text()='确认要删除该目标吗？']/../..//span[text()='确 定']/.."
删除成功断言="//span[text()='删除成功']"
勾选管理区数据库定位="//span[@title='${var[0][0]}']/../span[2]"
点击管理区数据库定位="//li[text()='${var[0][0]}']"

