# Can be used in the test data like ${MyObject()} or ${MyObject(1)}
class MyObject:
    def __init__(self, index=''):
        self.index = index
    def __str__(self):
        return '<MyObject%s>' % self.index
    

账号输入框="//input[@type='text']"
密码输入框="//input[@type='password']"
##########银行托收明细##########
银行托收明细_资源树搜索框="//input[@id='txtSerachTerm']"
核销时段_开始时间="//input[@id='PaymentStartDate']"
核销时段_结束时间="//input[@id='PaymentEndDate']"
银行托收明细_只显示本月费用="//input[@id='IsShowThisMonthOnly']"
银行托收明细_导出="//button[@id='btnExportCustomerSummary']"
##########已收费用日报##########
已收费用日报_本期往期汇总tab="//ul[@id='tabHeader']/li[2]"
已收费用日报_按收费项目汇总tab="//ul[@id='tabHeader']/li[3]"
已收费用日报_收费明细tab="//ul[@id='tabHeader']/li[4]"
已收费用日报_票据汇总tab="//ul[@id='tabHeader']/li[5]"
已收费用日报_资源树搜索框="//input[@id='txtSerachTerm']"

已收费用日报_收款日期="//input[@id='daySelectRange']"
已收费用日报_选择收款日期_今年="//div[@class='ranges']/ul/li[5]"
已收费用日报_选择收款日期_本月="//div[@class='ranges']/ul/li[2]"
已收费用日报_收费项目下拉="//select[@id='chargeItemTypeId']/following-sibling::span"
已收费用日报_选择收费项目="//select[@id='chargeItemTypeId']/option[1]"
已收费用日报_房产管理员下拉="//input[@id='managerId']/following-sibling::span"
已收费用日报_选择房产管理员="//ul[@class='select2-results__options']/li[1]"
已收费用日报_收费员下拉="//input[@id='operatorId']/following-sibling::span"
已收费用日报_选择收费员="//ul[@class='select2-results__options']/li[1]"
已收费用日报_付款方式下拉="//select[@id='paidMethods']/following-sibling::span"
已收费用日报_选择付款方式="//ul[@id='select2-paidMethods-results']/li[1]"
已收费用日报_按收款日期汇总_导出="//button[@id='btnExportDetail']"

已收费用日报_按收费项目汇总_表格数据="//div[@id='gridDayPayments']/div/table/tbody/tr[1]/td[2]"
已收费用日报_按收费项目汇总_导出="//button[@id='btnExportSummary']"
已收费用日报_按收费项目汇总_显示收费标准="//div[@id='uniform-showChargeItem']/span"

已收费用日报_收费明细_资源详情="//div[@id='gridDayPaymentDetail']/div/table/tbody/tr[1]/td[1]/a"
已收费用日报_收费明细_客户详情="//div[@id='gridDayPaymentDetail']/div/table/tbody/tr[1]/td[2]/a"
已收费用日报_收费明细_导出="//button[@id='btnExportDetail']"

已收费用日报_票据汇总_表格数据="//div[@id='gridDayPaymentTickets']/div/table/tbody/tr[1]"
已收费用日报_票据汇总_导出="//button[@id='btnExportTicket']"
##########综合报表##########
综合报表_资源树搜索框="//input[@id='txtSerachTerm']"
综合报表_指定收费项目="//input[@class='select2-search__field']"
综合报表_选择一个收费项目="//ul[@id='select2-ChargeItemTypeIds-results']/li[1]"
综合报表_费用应收日期开始="//input[@id='ShouldChargeStartDate']"
综合报表_费用应收日期结束="//input[@id='ShouldChargeEndDate']"
综合报表_是否包含滞纳金="//input[@id='IsContainsLateFee']"
综合报表_汇总Tab="//ul[@id='tabHeader']/li[1]"
综合报表_汇总_显示管理区="//div[@id='uniform-summaryShowRegion']"
综合报表_汇总_显示楼宇="//div[@id='uniform-summaryShowBuilding']"
综合报表_汇总_显示资源="//div[@id='uniform-summaryShowResource']"
综合报表_汇总_显示收费项目="//div[@id='uniform-summaryShowChargeItemType']"
综合报表_汇总_显示月份="//div[@id='uniform-summaryShowMonth']"
综合报表_汇总_显示年份="//div[@id='uniform-summaryShowYear']"
综合报表_汇总_导出="//button[@id='btnExport']"
综合报表_汇总_确定="//button[@id='btnConfirmSummary']"
综合报表_汇总_表格="//div[@id='grid']"
综合报表_按年度汇总Tab="//ul[@id='tabHeader']/li[2]"
综合报表_按年度汇总_显示管理区="//div[@id='uniform-yearSummaryShowRegion']"
综合报表_按年度汇总_显示楼宇="//div[@id='uniform-yearSummaryShowBuilding']"
综合报表_按年度汇总_显示资源="//div[@id='uniform-yearSummaryShowResource']"
综合报表_按年度汇总_显示收费项目="//div[@id='uniform-yearSummaryShowChargeItemType']"
综合报表_按年度汇总_确定="//button[@id='btnConfirmYearSummary']"
综合报表_按年度汇总_表格="//div[@id='gridYearSummary']"
综合报表_按月度汇总Tab="//ul[@id='tabHeader']/li[3]"
综合报表_按月度汇总_显示管理区="//div[@id='uniform-monthSummaryShowRegion']"
综合报表_按月度汇总_显示楼宇="//div[@id='uniform-monthSummaryShowBuilding']"
综合报表_按月度汇总_显示资源="//div[@id='uniform-monthSummaryShowResource']"
综合报表_按月度汇总_显示收费项目="//div[@id='uniform-monthSummaryShowChargeItemType']"
综合报表_按月度汇总_确定按钮="//button[@id='btnConfirmMonthSummary']"
综合报表_按月度汇总_表格="//div[@id='gridMonthSummary']"
综合报表_按收费项目汇总Tab="//ul[@id='tabHeader']/li[4]"
综合报表_按收费项目汇总_显示管理区="//div[@id='uniform-chargeItemTypeShowRegion']"
综合报表_按收费项目汇总_显示楼宇="//div[@id='uniform-chargeItemTypeShowBuilding']"
综合报表_按收费项目汇总_显示资源="//div[@id='uniform-chargeItemTypeShowResource']"
综合报表_按收费项目汇总_月份="//div[@id='uniform-chargeItemTypeShowMonth']"
综合报表_按收费项目汇总_确定="//button[@id='btnConfirmChargeItemSummary']"
综合报表_按收费项目汇总_表格="//div[@id='gridChargeItemTypeSummary']"
综合报表_清单明细Tab="//ul[@id='tabHeader']/li[5]"
综合报表_清单明细_表格="//div[@id='contentArea']"
##########现金收款明细##########
现金收款明细_资源树搜索框="//input[@id='txtSerachTerm']"
现金收款明细_指定收费项目="//ul[@class='select2-selection__rendered']"
现金收款明细_选择一个收费项目="//select[@id='ChargeItemTypeIds']/option[1]"
现金收款明细_收费时段开始日期="//input[@id='PaymentStartDate']"
现金收款明细_收费时段结束日期="//input[@id='PaymentEndDate']"
现金收款明细_表格="//div[@id='gridCashPayDetail']"
现金收款明细_搜索="//button[@id='btnSearch']"
现金收款明细_导出="//button[@id='btnExportCustomerSummary']"
##########预存转实收明细##########
预存转实收明细_资源树搜索框="//input[@id='txtSerachTerm']"
预存转实收明细_核销时间开始日期="//input[@id='PaymentStartDate']"
预存转实收明细_核销时间结束日期="//input[@id='PaymentEndDate']"
预存转实收明细_只显示本月费用="//input[@id='IsShowThisMonthOnly']/.."
预存转实收明细_表格="//div[@id='gridAdvancePayDetail']"
预存转实收明细_表格数据="//div[@id='gridAdvancePayDetail']/div[2]//tbody/tr[1]/td[@role='gridcell'][1]"
预存转实收明细_导出="//button[@class='btn btn-primary']"
##########应收实收预存一览##########
应收实收预存一览_收费项目="//span[@id='select2-chargeItemType-container']/parent::span"
应收实收预存一览_选择收费项目="//ul[@id='select2-chargeItemType-results']/li[1]"
应收实收预存一览_统计截止日期="//div[@id='datetimepicker']//button"
应收实收预存一览_选择统计截止日期="//div/div[4]//tbody//span[1]"
应收实收预存一览_表格="//div[@id='grid']"
应收实收预存一览_导出="//button[@id='btnExport']"
##########预存款收支明细##########
预存款收支明细_开始日期="//input[@id='startDate']/following-sibling::span"
预存款收支明细_选择开始日期="//div[@id='startDate_dateview']//tbody//tr[1]/td[1]/a"
预存款收支明细_结束日期="//input[@id='endDate']/following-sibling::span"
预存款收支明细_选择结束日期="//div[@id='endDate_dateview']//tbody//tr[last()]/td[last()]/a"
预存款收支明细_管理区="//select[@id='RegionId']"
预存款收支明细_选择管理区="//select[@id='RegionId']/option[2]"
预存款收支明细_收费项目下拉="//span[@id='select2-ChargeItemTypeId-container']/parent::span"
预存款收支明细_选择收费项目="//select[@id='ChargeItemTypeId']/option[1]"
预存款收支明细_房间代码="//input[@id='Code']"
预存款收支明细_客户="//input[@id='CustomerName']"
预存款收支明细_搜索="//button[@id='btnFilterDetail']"
预存款收支明细_表格="//div[@id='gridDepositChargeDetailReport']"
预存款收支明细_房间详情="//div[@id='gridDepositChargeDetailReport']//tr[1]/td[3]"
预存款收支明细_客户详情="//div[@id='gridDepositChargeDetailReport']//tr[1]/td[5]"
预存款收支明细_导出="//button[@id='btnExport']"
##########住户缴费日期报表##########
住户缴费日期报表_管理区="//div[@id='regionId']"
住户缴费日期报表_选择管理区="//div[@id='regionId']/following-sibling::div//ul/li[1]"
住户缴费日期报表_楼宇="//div[@id='buildingId']"
住户缴费日期报表_选择楼宇="//div[@id='buildingId']/following-sibling::div//ul/li[1]"
住户缴费日期报表_资源代码="//input[@id='houseNumber']"
住户缴费日期报表_客户="//input[@id='customerName']"
住户缴费日期报表_收费标准="//div[@id='chargeItemId']"
住户缴费日期报表_选择收费标准="//div[@id='chargeItemId']/following-sibling::div//ul/li[1]"
住户缴费日期报表_重置="//form/div[3]//div/button[1]"
住户缴费日期报表_搜索="//form/div[3]//div/button[2]"
住户缴费日期报表_搜索2="//div[@id='root']//button[2]"
住户缴费日期报表_表格="//div[@class='ant-table-content']/div[1]//table"
住户缴费日期报表_房间详情="//div[@class='ant-table-content']/div[1]//tr[1]/td[3]"
住户缴费日期报表_客户详情="//div[@class='ant-table-content']/div[1]//tr[1]/td[4]"
住户缴费日期报表_导出="//div[@class='ListButton___2jlS-']//button"
##########微信支付明细##########
微信支付明细_资源树搜索框="//input[@id='txtSerachTerm']"
微信支付明细_收费项目="//select[@id='ChargeItemTypeIds']/following-sibling::span"
微信支付明细_选择收费项目="//ul[@id='select2-ChargeItemTypeIds-results']/li[1]"
微信支付明细_收费日期开始="//input[@id='PaymentStartDate']"
微信支付明细_收费日期结束="//input[@id='PaymentEndDate']"
微信支付明细_导出="//button[@id='btnExportWeChatPayReport']"
微信支付明细_表格="//div[@id='gridAdvancePayDetail']"
##########微信支付提现对账##########
微信支付提现对账_年份="//div[@class='content___3M67u']/div[1]/div[1]/div[1]/div[1]/div[1]/div[@class='ant-select-selection__rendered']"
微信支付提现对账_选择年份="//body/div[2]//ul/li[last()]"
微信支付提现对账_月份="//div[@class='content___3M67u']/div[1]/div[1]/div[2]/div[1]/div[1]/div[@class='ant-select-selection__rendered']"
微信支付提现对账_选择月份="//body/div[3]//ul/li[last()]"
微信支付提现对账_日账单="//div/div[3]/button[@class='ant-btn']"
微信支付提现对账_月账单="//div/div[4]/button[@class='ant-btn']"
##########报表统计##########
报表统计_资源="//span[@class='ant-select-selection__rendered']/parent::span"
报表统计_选择资源="//ul[@class='ant-select-tree']/li[1]/span[2]"
报表统计_时间段="//span[@id='date']"
报表统计_时间段_开始="//div[@class='ant-calendar-range-part ant-calendar-range-left']//tbody/tr[1]/td[1]"
报表统计_时间段_结束="//div[@class='ant-calendar-range-part ant-calendar-range-right']//tbody/tr[last()]/td[1]"
报表统计_收费项目="//div[@id='chargeItemTypeId']"
报表统计_选择收费项目="//div[@id='chargeItemTypeId']/following-sibling::div//ul/li[1]"
报表统计_计费方式="//div[@id='calculationMethod']"
报表统计_选择计费方式="//div[@id='calculationMethod']/following-sibling::div//ul/li[1]"
报表统计_重置="//form/div[3]/div[1]/button[1]"
报表统计_搜索="//form/div[3]/div[1]/button[2]"
报表统计_表格="//table"
报表统计_房间详情="//div[@class='ant-table-content']/div[1]//tr[1]/td[3]"
报表统计_客户详情="//div[@class='ant-table-content']/div[1]//tr[1]/td[6]"
报表统计_导出="//div[@class='ListButton___2jlS-']//button[@class='ant-btn']"
##########保证金收退明细##########
保证金收退明细_管理区="//div[@id='regionId']"
保证金收退明细_选择管理区="//body/div[2]//ul/li[1]"
保证金收退明细_合同编号="//input[@id='contractNumber']"
保证金收退明细_房间车位="//input[@id='organizationItemCode']"
保证金收退明细_楼宇停车场="//div[@id='buildingId']"
保证金收退明细_选择楼宇停车场="//body/div[3]//ul/li[1]"
保证金收退明细_收款日期="//span[@id='dateOfReceipt']"
保证金收退明细_收款日期_开始="//div[@class='ant-calendar-range-part ant-calendar-range-left']//tbody/tr[1]/td[1]"
保证金收退明细_收款日期_结束="//div[@class='ant-calendar-range-part ant-calendar-range-right']//tbody/tr[last()]/td[1]"
保证金收退明细_收费标准="//div[@id='chargeItemId']"
保证金收退明细_选择收费标准="//body/div[5]//ul/li[1]"
保证金收退明细_重置="//form/div[1]//div/button[1]"
保证金收退明细_搜索="//form/div[1]//div/button[2]"
保证金收退明细_表格="//table"
保证金收退明细_导出="//div/div[1]/div[1]/button"
##########合同费用汇总表##########
合同费用汇总表_管理区="//div[@id='regionId']"
合同费用汇总表_选择管理区="//div[@id='regionId']/following-sibling::div//ul/li[1]"
合同费用汇总表_时间段="//span[@id='date']//input"
合同费用汇总表_选择月份="//table[@class='ant-calendar-month-panel-table']//tr[1]/td[1]"
合同费用汇总表_重置="//form[@class='ant-form ant-form-horizontal']//button[@class='ant-btn']"
合同费用汇总表_搜索="//div[@class='ant-col ant-col-24']/button[@class='ant-btn ant-btn-primary']"
合同费用汇总表_重置="//form/div[2]//div/button[1]"
合同费用汇总表_搜索="//form/div[2]//div/button[2]"
合同费用汇总表_重置="//form/div[3]//div/button[1]"
合同费用汇总表_搜索="//form/div[3]//div/button[2]"
合同费用汇总表_表格="//table"
合同费用汇总表_导出="//div[@class='ListButton___2jlS-']//button[@class='ant-btn']"
##########往年收欠率表##########
往年收欠率表_截止日期="//span[@id='date']//input[1]"
往年收欠率表_选择开始日期="//div[@class='ant-calendar-range-part ant-calendar-range-left']//tbody/tr[2]/td[1]"
往年收欠率表_选择截止日期="//div[@class='ant-calendar-range-part ant-calendar-range-right']//tbody/tr[2]/td[1]"
往年收欠率表_管理区="//span[text()='请选择管理区']"
往年收欠率表_选择管理区=""
往年收欠率表_收费项目="//div[@id='chargeItemTypeIds']"
往年收欠率表_选择收费项目="//ul[@role='listbox']/li[1]"
往年收欠率表_重置="//button/span[text()='重 置']/.."
往年收欠率表_搜索="//button/span[text()='搜 索']/.."
往年收欠率表_导出="//button/span[text()='导出EXCEL']/.."
往年收欠率表_表格="//table"
##########综合收费率报表##########
综合收费率报表_截止月份="//span[@id='date']//input"
综合收费率报表_选择截止月份="//a[text()='今天']"
综合收费率报表_管理区="//ul[@class='ant-select-selection__rendered']/parent::span"
综合收费率报表_选择管理区="//ul[@class='ant-select-tree']/li/ul/li[1]/span[3]"
综合收费率报表_收费项目="//div[@id='chargeItemTypeIds']"
综合收费率报表_选择收费项目="//body/div[4]//ul/li[1]"
综合收费率报表_重置="//form/div[1]//span/button[1]"
综合收费率报表_搜索="//form/div[1]//span/button[2]"
综合收费率报表_导出="//button[@class='ant-btn']"
综合收费率报表_表格="//table"
综合收费率报表_合计本年应收="//div[@class='ant-table-footer']//tbody/tr[1]/td[5]"
综合收费率报表_本年应收搜索输入框="//body/div[3]//span/input"
综合收费率报表_本年应收搜索按钮="//span[@class='ant-input-suffix']"
综合收费率报表_本年应收表格="//body/div[3]//table"