# Can be used in the test data like ${MyObject()} or ${MyObject(1)}XIUGAI
class MyObject:
    def __init__(self, index=''):
        self.index = index
    def __str__(self):
        return '<MyObject%s>' % self.index
    


账号输入框="//input[@type='text']"
密码输入框="//input[@type='password']"
##########销售单管理##########
销售单管理_新建按钮="//button/span[text()='新 建']/.."
新建销售单_销售单号="//button[@class='ant-modal-close']/following-sibling::div[2]//input[@id='salesOrderNumber']"
新建销售单_是否中奖="//input[@id='isWinning']"
新建销售单_顾客姓名="//input[@id='buyerName']"
新建销售单_联系电话="//input[@id='phoneNumber']"
新建销售单_展厅号="//button[@class='ant-modal-close']/following-sibling::div[2]//div[@id='organizationItemId']"
新建销售单_选择展厅号="//ul[@role='listbox']/li[1]"
新建销售单_展厅名称="//div[@id='customerId']"
新建销售单_选择展厅名称="//div[@style='position: absolute; top: 0px; left: 0px; width: 100%;'][2]//ul[@role='listbox']/li[1]"
新建销售单_收款金额="//form/div[4]//input[@class='ant-input-number-input']"
新建销售单_收款方式="//button[@class='ant-modal-close']/following-sibling::div[2]//div[@id='paidMethodId']"
新建销售单_选择收款方式="//ul[@role='listbox']/li[text()='现金']"
新建销售单_收款时间="//button[@class='ant-modal-close']/following-sibling::div[2]//span[@id='paidDate']"
新建销售单_收款时间选择此刻="//span/a[@class='ant-calendar-today-btn ']"
新建销售单_抽奖楼层="//input[@id='lotteryFloors']"
新建销售单_新建抽奖时间段="//div[@id='lotteryPeriodId']/following-sibling::span/a"
新建销售单_新建抽奖时间段开始时间="//input[@id='startDate']"
新建销售单_新建抽奖时间段结束时间="//input[@id='endDate']"
新建销售单_新建抽奖时间段确定="//body/div[7]//button[@class='ant-btn ant-btn-primary']"
新建销售单_抽奖时间段="//button[@class='ant-modal-close']/following-sibling::div[2]//div[@id='lotteryPeriodId']"
新建销售单_选择抽奖时间段="//body/div[7]//ul/li[1]"
新建销售单_手续费="//form/div[6]//input[@class='ant-input-number-input']"
新建销售单_刷卡卡号="//input[@id='cardNumber']"
新建销售单_确定="//div[@class='ant-modal-footer']//button[2]"
搜索销售单_销售单号="//main/div[1]//input[@id='salesOrderNumber']"
搜索销售单_展厅号="//main/div[1]//div[@id='organizationItemId']"
搜索销售单_选择展厅号="//main/div[1]//div[@id='organizationItemId']/following-sibling::div//ul/li[1]"
搜索销售单_收款方式="//main/div[1]//div[@id='paidMethodId']"
搜索销售单_选择收款方式="//main/div[1]//div[@id='paidMethodId']/following-sibling::div//ul/li[1]"
搜索销售单_收款时间="//main/div[1]//span[@id='paidDate']"
搜索销售单_抽奖时间段="//main/div[1]//div[@id='lotteryPeriodId']"
搜索销售单_选择抽奖时间段="//main/div[1]//div[@id='lotteryPeriodId']/following-sibling::div//ul/li[1]"
搜索销售单_是否中奖="//div[@id='isWinning']"
搜索销售单_中奖="//div[@id='isWinning']/following-sibling::div//ul/li[1]"
搜索销售单_确定按钮="//form/div[3]//button[2]"
销售单管理_编辑按钮="//div[@class='ant-table-fixed-right']//tbody/tr[1]//span/a[1]"
销售单管理_删除按钮="//div[@class='ant-table-fixed-right']//tbody/tr[1]//span/a[2]"
销售单管理_确认删除按钮="//button[@class='ant-btn ant-btn-primary ant-btn-sm']"
销售单管理_导出按钮="//div[@class='ListButton___2jlS-']//button[@class='ant-btn']"
销售单管理_高级搜索展开="//a[@class='seniorSearchBtn']"
销售单管理_简单搜索输入框="//input[@class='ant-input ant-input-lg']"
销售单管理_简单搜索按钮="//span[@class='ant-input-suffix']"
##########返款管理##########
返款管理_新建按钮="//button/span[text()='新建返款']/.."
新建返款_展厅号="//button[@class='ant-modal-close']/following-sibling::div[2]//div[@id='organizationItemId']"
新建返款_输入框="//button[@class='ant-modal-close']/following-sibling::div[2]//div[@id='organizationItemId']//input"
新建返款_销售单收款时间段="//button[@class='ant-modal-close']/following-sibling::div[2]//span[@class='ant-calendar-picker-input ant-input']"
新建返款_销售单收款开始时间="//div[@class='ant-calendar-date-panel']/div[1]//div[@class='ant-calendar-body']//tbody/tr[1]/td[1]/div[1]"
新建返款_销售单收款结束时间="//div[@class='ant-calendar-date-panel']/div[2]//div[@class='ant-calendar-body']//tbody/tr[last()]/td[last()]/div[last()]"
新建返款_手续费="//input[@id='serviceCharge']"
新建返款_押金="//input[@id='depositAmount']"
新建返款_活动费用="//input[@id='activityCost']"
新建返款_立柱费="//input[@id='postFee']"
新建返款_广告制作费="//input[@id='advertisingCost']"
新建返款_活动未达标扣款="//input[@id='deductAmount']"
新建返款_其他费用="//input[@id='otherAmount']"
新建返款_应返款金额="//input[@id='refundTotalAmount']"
新建返款_抵扣物业费="//input[@id='propertyFee']"
新建返款_抵扣租金="//input[@id='rent']"
新建返款_抵扣水费="//input[@id='waterFee']"
新建返款_抵扣电费="//input[@id='electricityFee']"
新建返款_抵扣空调费="//input[@id='airConditioningFee']"
新建返款_确定="//div[@class='ant-modal-footer']//button[2]"
返款管理_编辑按钮="//div[@class='ant-table-fixed-right']//tbody/tr[1]//span/a[1]"
返款管理_返款按钮="//div[@class='ant-table-fixed-right']//tbody/tr[1]//span/a[2]"
返款管理_导出按钮="//div[@class='ListButton___2jlS-']//div/button[2]"
返款管理_打印返款="//div[@class='ListButton___2jlS-']//div/button[3]"
返款管理_高级搜索展开="//a[@class='seniorSearchBtn']"
返款管理_简单搜索输入框="//input[@class='ant-input ant-input-lg']"
返款管理_简单搜索按钮="//span[@class='ant-input-suffix']"
搜索返款_展厅号="//main/div[1]//div[@id='organizationItemId']"
搜索返款_选择展厅号="//main/div[1]//div[@id='organizationItemId']/following-sibling::div//ul/li[1]"
搜索返款_展厅名称="//main/div[1]//div[@id='customerId']"
搜索返款_选择展厅名称="//main/div[1]//div[@id='customerId']/following-sibling::div//ul/li[1]"
搜索返款_返款时间="//main/div[1]//span[@id='refundDate']"
搜索返款_返款开始时间="//div[@class='ant-calendar-date-panel']/div[1]//div[@class='ant-calendar-body']//tbody/tr[1]/td[1]/div[1]"
搜索返款_返款结束时间="//div[@class='ant-calendar-date-panel']/div[2]//div[@class='ant-calendar-body']//tbody/tr[last()]/td[last()]/div[last()]"
搜索返款_返款状态="//main/div[1]//div[@id='status']"
搜索返款_选择返款状态="//main/div[1]//div[@id='status']/following-sibling::div//ul/li[2]"
搜索返款_确定按钮="//form/div[3]//button[2]"