# Can be used in the test data like ${MyObject()} or ${MyObject(1)}XIUGAI
class MyObject:
    def __init__(self, index=''):
        self.index = index
    def __str__(self):
        return '<MyObject%s>' % self.index
    
#新建合同
新建合同按钮="//button[@id='btnAdd']"
选择管理区下拉按钮="//div[@id='RegionId']//i"
下拉选择第一个管理区="//div[@id='RegionId']/following-sibling::div[1]//li[1]"
选择租户下拉按钮="//div[@id='RenterField']//i"
下拉选择第一个租户="//div[@id='RenterField']/following-sibling::div[1]//li[1]"
合同编号输入框="//input[@id='Number']"
合同名称输入框="//input[@id='Name']"
合同备注输入框="//textarea[@id='Remark']"
添加房间按钮="//div[@class='ant-card-extra']/button"
楼栋下拉按钮="//li[@class='ant-tree-treenode-switcher-close'][1]/span[@class='ant-tree-switcher ant-tree-switcher_close']"
楼栋下拉选择房间="//li[@class='ant-tree-treenode-switcher-close'][1]//span[@class='ant-tree-checkbox-inner']"
确认添加房间="//div[@class='ant-modal-footer']/div/button[@class='ant-btn ant-btn-primary']"
合同下一步按钮="//button[@class='ant-btn ant-btn-primary']"
展开租赁标准="//div[11]//div[@class='ant-select ant-select-enabled'][1]/div[@class='ant-select-selection ant-select-selection--single']//i[@class='anticon anticon-down ant-select-arrow-icon']"
选择租赁收费标准="//div[12]//li[@class='ant-select-dropdown-menu-item ant-select-dropdown-menu-item-active']/font/font"
合同规则添加按钮="//div[@class='ant-card emptyTermCard___2Kcy2 ant-card-bordered'][1]//button[@class='ant-btn']"
保证金额输入="//input[@id='FixedAmount-depositTerm-0']"
减免标准下拉="//div[@id='LeaseTermIndex-discountTerm-0']//i"
选择减免标准="//div[@style='position: absolute; top: 0px; left: 0px; width: 100%;'][1]//li"
选择减免周期="//span[@id='EffectiveDate-discountTerm-0']/span"
选择减免日期开始="//td[@class='ant-calendar-cell ant-calendar-today ant-calendar-selected-date']"
选择减免日期结束="//td//div[@aria-selected='true']/../following-sibling::td[1]/div"
生成账单按钮保存="//span/button[@class='ant-btn ant-btn-primary']"
核对账单保存="//div[@class='ant-modal-confirm-btns']/button[@class='ant-btn ant-btn-primary']"
#搜索合同
搜索合同输入框="//input[@id='searchTerm']"
普通搜索按钮="//button[@id='btnFilter']"
高级搜索展开按钮="//button[@class='btn filter-collapse-toggle']"
搜索合同编号输入框="//input[@id='ContractNumber']"
搜索合同名称输入框="//input[@id='ContractName']"
高级搜索按钮="//button[@id='btnFilterDetail']"
搜索结果断言="//table[@class='k-selectable']/tbody/tr/td[3]"
#合同变更="
合同变更按钮="//button[@id='btnEdit']"
合同审核按钮="//button[@id='btnExecute']"
审核成功断言="//font[text()='合同已执行']"
确认审核成功="//div[@class='modal-dialog']//button[@class='btn btn-primary']"
续签合同按钮="//button[@id='btnRewnew']"
删除续签合同保证金="//div[@class='ant-card termCard___wE8b4 ant-card-bordered'][2]//button[@class='ant-btn ant-btn-icon-only']"
二次确认="//button[@class='ant-btn ant-btn-primary ant-btn-sm']"
删除续签合同减免条款="//div[@class='ant-card termCard___wE8b4 ant-card-bordered'][2]//button[@class='ant-btn ant-btn-icon-only']"
删除合同按钮="//button[@id='btnDelete']"
二次删除确认="//a[@class='btn btn-sm btn-danger']"
删除成功断言="//font[text()='1条记录删除成功！']"
#合同收费
合同名称输入框2="//input[@id='contractName']"
选择合同账单="//div[@id='gridBills']/div//table//tr[1]/td[8]"
调整合同费用="//button[@id='btnBillAdjust']"
选择增加合同费用="//label[@class='radio-inline'][2]/div[@class='radio']/span/input"
调整价钱输入框="//input[@id='changeScope']"
调整原因="//textarea[@id='Description']"
调整确定按钮="//button[@id='btnBillAdjustConfirm']"
确定调整成功="//div[@class='modal-dialog']//button[@class='btn btn-primary']"
实收金额="//input[@id='ChargeAmount']"
付款方式选择="//span[@id='select2-PaidMethodId-container']"
选择现金付款="//ul[@id='select2-PaidMethodId-results']/li[1]"
确认付款="//button[@id='btnPaymentPreview']"
确认但不打印按钮="//button[@id='btnPaymentConfirm']"
收费成功断言="//div[text()='收费成功！']"
收费成功确定按钮="//div[@class='modal-dialog']//button[@class='btn btn-primary']"
空白框="//div[@id='gridBills']/div[@class='k-grid-content k-auto-scrollable']"
#生成合同账单
合同名称span="//div/input[@id='ContractId']/../span/span/span"
合同名称输入框1="//input[@class='select2-search__field']"
选择第一个合同="//ul[@id='select2-ContractId-results']/li[1]"
点击搜索按钮="//button[@id='btnFilterDetail']"
确定生成账单="//button[@id='GenerateBill']"
账单生成成功断言="//div[text()='生成合同账单完成！']"
生成账单成功确定="//div[@class='modal-content']//button[@class='btn btn-primary']"


